export let wishes = ["Happy Valentine’s Day! My favorite place in the world is right next to you.",
"You may hold my hand for awhile, but you hold my heart forever.",
"The best things in life are better with you.",
"Whenever I feel like giving up, your love keeps me going.",
"I never believed in luck until I found you.",
"I met you. I liked you. I love you. I’m keeping you.",
"Whenever I'm with you, wherever we are, I'm home.",
"Every love story is wonderful but ours is my favorite.",
"You’re the one. I’ve never been so sure of anything in my whole life.",
"I fell in love with you because of all the small things you don’t even realize you’re doing.",
"Thank you for making me laugh and smile every single day since the day we met.",
"Like you and me, some things are just meant to be.",
"I’m a better person because of you.",
"Happy Valentine’s Day! Are you seriously not sick of me yet?",
"I’m yours. Sorry, no refunds or exchanges.",
"So happy we both swiped right.",
"I love you. Though I like you a lot better after my first cup of coffee.",
"I’m so happy and thankful to have found someone as weird as me.",
"All I need in this life is you and me. Oh, and WiFi. And wine. And snacks. But that’s it, I swear.",
"You have the worst taste in TV shows, and I’m still madly in love with you. That’s how you know it’s real.",
"Besides cheese, you are my favorite.",
"I love you because you're the person who annoys me the least.",
"You know how I knew you were the one? You’re the only person I can stand for longer than 6 hours.",
"I know loving me isn’t always the easiest. But trust me, I’m worth it.",
"Happy Valentine’s Day! Nothing says love like a piece of paper folded in half with some words on it.",
"Happy Valentine’s Day! Thanks for being my person.",
"Our friendship is #relationshipgoals.",
"We’ve been friends for so long that we’re basically married. I now owe you a Valentine’s Day card every year.",
"You’re the Tina Fey to my Amy Poehler. (Or, any pop culture duo you love!)",
"Making friends as a grown-up is hard. Thank you for making it easy.",
"Good times. Bad Times. Fun Times. Tough times. No matter what, you’re always by my side.",
"I love that you're my emergency contact.",
"Friend love is the best kind of love. We’ll never break up because you refuse to pick up your socks.",
"We go together like wine and any day of the week.",
"Who needs a Valentine when I have a best friend like you?",
"Happy Valentine’s Day! Just wanted to let you know that you are LOVED.",
"“I would rather share one lifetime with you than face all the ages of this world alone.” — Arwen in The Lord of the Rings",
"“When you realize you want to spend the rest of your life with somebody, you want the rest of your life to start as soon as possible.” — Harry in When Harry Met Sally",
"“To me, you are perfect.” — Mark in Love Actually",
"“I’m scared of walking out of this room and never feeling the rest of my whole life the way I feel when I’m with you.” — Baby in Dirty Dancing",
"“I want all of you, forever, you and me, every day.” — Noah in The Notebook",
"“I’ve come here with no expectations, only to profess now that I am at liberty to do so, that my heart is, and always will be, yours.” — Edward in Sense and Sensibility",
"“I am in love with you. I know that love is just a shout into the void and that oblivion is inevitable. And that we’re all doomed and that one day all of our labors will be returned to dust. And I know the sun will swallow the only Earth we will ever have. And I am in love with you.” — Gus in The Fault in Our Stars",
"“I think I’d miss you even if we’d never met.” — Nick in The Wedding Date",
"“You have bewitched me, body and soul. I love, I love, I love you. I never wish to be parted from you from this day on.” — Mr. Darcy in Pride & Prejudice",
"“When first we fall in love, we feel that we know all there is to know about life, and perhaps we are right.”— Mignon McLaughlin",
"“Love doesn't make the world go 'round. Love is what makes the ride worthwhile.” — Franklin P. Jones",
"“Love is life. All, everything that I understand, I understand only because I love. Everything is, everything exists, only because I love.” — Leo Tolstoy",
"“It is a curious thought, but it is only when you see people looking ridiculous, that you realize just how much you love them.” — Agatha Christie",
"“Much love much trial, but what an utter desert is life without love.” — Charles Darwin",
"“I don’t want to live—I want to love first, and live incidentally.” — Zelda Fitzgerald",
"“Love does not consist in gazing at each other but in looking outward together in the same direction” — Antoine de Saint-Exupery",
"“Of all forms of caution, caution in love is perhaps most fatal to true happiness.” —Bertrand Russell",
"“Love doesn't just sit there, like a stone, it has to be made, like bread; remade all the time, made new.” — Ursula K. Le Guin",
"“When we love, we always strive to become better than we are. When we strive to become better than we are, everything around us becomes better too.” — Paulo Coelho"];